## 1. Import NumPy

Let's start by importing NumPy and verifying the installation by checking the version.

In [1]:
import numpy as np

# Check the version of NumPy
print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.5


## 2. Understanding NumPy Arrays

NumPy arrays are the fundamental data structure in NumPy. They are more efficient than Python lists for numerical operations and offer several advantages:

- **Performance**: NumPy arrays are much faster than Python lists for numerical operations
- **Memory Efficiency**: They use less memory than Python lists
- **Convenience**: They provide a convenient way to work with numerical data
- **Broadcasting**: They support element-wise operations

Key properties of arrays:
- **shape**: The dimensions of the array
- **dtype**: The data type of array elements
- **size**: The total number of elements in the array

In [3]:
# Create a simple array
arr = np.array([1, 2, 3, 4, 5])

# Display array properties
print(f"Array: {arr}")
print(f"Shape: {arr.shape}")
print(f"Data type: {arr.dtype}")
print(f"Size: {arr.size}")
print(f"Dimensions: {arr.ndim}")

Array: [1 2 3 4 5]
Shape: (5,)
Data type: int64
Size: 5
Dimensions: 1


## 3. Creating Arrays

NumPy provides various methods to create arrays. Let's explore the most common ones.

In [4]:
# Method 1: From Python lists
arr_from_list = np.array([1, 2, 3, 4, 5])
print(f"From list: {arr_from_list}")

# Method 2: 2D array from list of lists
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D array:\n{arr_2d}")

# Method 3: Using zeros() - creates array with all zeros
arr_zeros = np.zeros((3, 3))
print(f"\nZeros (3x3):\n{arr_zeros}")

# Method 4: Using ones() - creates array with all ones
arr_ones = np.ones((2, 4))
print(f"\nOnes (2x4):\n{arr_ones}")

# Method 5: Using arange() - creates array with evenly spaced values
arr_arange = np.arange(0, 10, 2)
print(f"\narange(0, 10, 2): {arr_arange}")

# Method 6: Using linspace() - creates array with specified number of evenly spaced values
arr_linspace = np.linspace(0, 1, 5)
print(f"\nlinspace(0, 1, 5): {arr_linspace}")

# Method 7: Using eye() - creates identity matrix
arr_eye = np.eye(3)
print(f"\nIdentity matrix (3x3):\n{arr_eye}")

# Method 8: Using random() - creates array with random values
arr_random = np.random.random((2, 3))
print(f"\nRandom array (2x3):\n{arr_random}")

From list: [1 2 3 4 5]

2D array:
[[1 2 3]
 [4 5 6]]

Zeros (3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones (2x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

arange(0, 10, 2): [0 2 4 6 8]

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array (2x3):
[[0.14348381 0.66370874 0.37844106]
 [0.60361096 0.86824952 0.06205106]]


## 4. Array Indexing and Slicing

Access individual elements and subsets of arrays using indexing and slicing.

In [ ]:
# 1D Array Indexing and Slicing
arr_1d = np.array([10, 20, 30, 40, 50])
print(f"Original array: {arr_1d}")
print(f"First element (index 0): {arr_1d[0]}")
print(f"Last element (index -1): {arr_1d[-1]}")
print(f"Elements from index 1 to 3: {arr_1d[1:4]}")
print(f"Every second element: {arr_1d[::2]}")

# 2D Array Indexing and Slicing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nOriginal 2D array:\n{arr_2d}")
print(f"Element at [1, 2]: {arr_2d[1, 2]}")
print(f"First row: {arr_2d[0, :]}")
print(f"First column: {arr_2d[:, 0]}")
print(f"Subarray [0:2, 1:3]:\n{arr_2d[0:2, 1:3]}")

## 5. Basic Array Operations

Perform element-wise arithmetic operations and scalar operations on arrays.

In [2]:
# Create two arrays for operations
arr_a = np.array([1, 2, 3, 4, 5])
arr_b = np.array([2, 3, 4, 5, 6])

print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")

# Element-wise operations
print(f"\nAddition (A + B): {arr_a + arr_b}")
print(f"Subtraction (A - B): {arr_a - arr_b}")
print(f"Multiplication (A * B): {arr_a * arr_b}")
print(f"Division (A / B): {arr_a / arr_b}")
print(f"Exponentiation (A ** 2): {arr_a ** 2}")

# Scalar operations
print(f"\nScalar operations:")
print(f"Add 10 to each element: {arr_a + 10}")
print(f"Multiply each element by 2: {arr_a * 2}")
print(f"Square root of each element: {np.sqrt(arr_a)}")

Array A: [1 2 3 4 5]
Array B: [2 3 4 5 6]

Addition (A + B): [ 3  5  7  9 11]
Subtraction (A - B): [-1 -1 -1 -1 -1]
Multiplication (A * B): [ 2  6 12 20 30]
Division (A / B): [0.5        0.66666667 0.75       0.8        0.83333333]
Exponentiation (A ** 2): [ 1  4  9 16 25]

Scalar operations:
Add 10 to each element: [11 12 13 14 15]
Multiply each element by 2: [ 2  4  6  8 10]
Square root of each element: [1.         1.41421356 1.73205081 2.         2.23606798]


## 6. Array Aggregation Functions

Use functions like sum(), mean(), std(), min(), and max() to compute aggregate statistics.

In [ ]:
# Create an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Array: {arr}")

# Aggregation functions
print(f"\nAggregation Functions:")
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard Deviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")
print(f"Minimum: {np.min(arr)}")
print(f"Maximum: {np.max(arr)}")
print(f"Product: {np.prod(arr)}")

# 2D array aggregations
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n2D Array:\n{arr_2d}")
print(f"\nAggregations along different axes:")
print(f"Sum of all elements: {np.sum(arr_2d)}")
print(f"Sum along axis 0 (columns): {np.sum(arr_2d, axis=0)}")
print(f"Sum along axis 1 (rows): {np.sum(arr_2d, axis=1)}")
print(f"Mean along axis 0: {np.mean(arr_2d, axis=0)}")
print(f"Mean along axis 1: {np.mean(arr_2d, axis=1)}")

## 7. Broadcasting

Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes. It automatically expands arrays to compatible shapes for operations.

In [ ]:
# Example 1: Scalar and array
arr = np.array([1, 2, 3, 4, 5])
scalar = 10
print(f"Array: {arr}")
print(f"Scalar: {scalar}")
print(f"Array + Scalar: {arr + scalar}")

# Example 2: 1D and 2D arrays
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n1D Array: {arr_1d}")
print(f"2D Array:\n{arr_2d}")
print(f"Adding 1D to each row of 2D:\n{arr_2d + arr_1d}")

# Example 3: Column and row broadcasting
column = np.array([[1], [2], [3]])
row = np.array([1, 2, 3, 4])
print(f"\nColumn shape: {column.shape}")
print(f"Row shape: {row.shape}")
print(f"Column + Row (broadcast to 3x4):\n{column + row}")

# Example 4: Element-wise operations with compatible shapes
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([10, 20])
print(f"\nArray A (2x2):\n{arr_a}")
print(f"Array B (1x2): {arr_b}")
print(f"A * B (broadcasting):\n{arr_a * arr_b}")